### ISSUE TITLE
TypeScript playground ideas

### ISSUE THREAD

**Issue by orta** [orta/typescript-notes#7]
- Should support importing @types - so you can make an example working with the node types etc
- templates could be improved ( could be scoped per type of projects (React/Node/Angular/jQuery) etc ) which could come with the types above
- snippets (like `keyof` `instanceof` ) which are like the complicatedy things you do once and forget
- Needs a way to format with prettier
- URLs can be broken in certain [markdown parsers](https://old.reddit.com/r/typescript/comments/bi0ib1/can_someone_explain_how_come_this_is_valid_and/elzayb5/)

**Comment by orta** [comment]
Could we just move https://github.com/agentcooper/typescript-play into the typescript org main website instead?

**Comment by orta** [comment]
Playground loading thing could be useful tips or "did you know"s

**Comment by sandersn** [comment]
ts-ast-viewer is pretty great

**Comment by orta** [comment]
could drop the 2nd window and make it useful metadata - https://microsoft.github.io/tsdoc/

**Comment by orta** [comment]
I left a lot of ideas in #14

**Comment by orta** [comment]
We should be able to use the typescript boot to generate a zip which can be sued as the TS version

**Comment by orta** [comment]
snippet are interesting, but everything else is now on the roadmap or shipped
